#!/usr/bin/env bash
# Parse a config/environments/<env>.xcconfig file once and emit every key=value
# row in a form Make can `-include` or a POSIX shell can `source`. Validation
# (the _HOST/_HOST_NAME scheme rule) runs against every key before any output
# is written, so a partial fragment never lands on stdout.
#
# Usage:
#   scripts/lib/emit-xcconfig-env.sh --format=make <xcconfig-path>
#   scripts/lib/emit-xcconfig-env.sh --format=sh   <xcconfig-path>
#
# Output contract per format:
#   make: header comment, then `KEY ?= VALUE` lines. `$` in VALUE is doubled
#         to `$$` so Make does not interpret `$x` as a variable reference.
#   sh:   header comment, then `KEY='VALUE'` lines. Each `'` in VALUE is
#         replaced with `'\''` (the standard POSIX single-quote escape).
#
# Behaviour notes:
#   - Empty values are omitted (so post-include `?=` fallbacks still fire,
#     matching the historical $(or $(call ...),default) pattern in the
#     Makefile).
#   - Missing xcconfig file: exit 0 with a header comment only. Matches the
#     silent-empty behaviour `make help` relies on for a fresh checkout.
#   - Newline in a value: hard error. xcconfig syntax does not permit it and
#     it would break both output formats.
#   - Validation failure on any key: exit 2 with the existing error format,
#     no stdout. The Makefile rule's `set -e` aborts the build before the
#     temp file is renamed into place.

set -euo pipefail

usage() {
  cat >&2 <<'USAGE'
Usage: emit-xcconfig-env.sh --format=make|sh <xcconfig-path>
USAGE
}

format=""
file=""
for arg in "$@"; do
  case "$arg" in
    --format=make|--format=sh) format="${arg#--format=}" ;;
    --format=*) printf 'unknown format: %s\n' "${arg#--format=}" >&2; usage; exit 64 ;;
    -h|--help) usage; exit 0 ;;
    --*) printf 'unknown option: %s\n' "$arg" >&2; usage; exit 64 ;;
    *) if [[ -n "$file" ]]; then usage; exit 64; fi; file="$arg" ;;
  esac
done

if [[ -z "$format" || -z "$file" ]]; then
  usage
  exit 64
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/xcconfig-validate.sh
. "${script_dir}/xcconfig-validate.sh"

header_make="# Generated by scripts/lib/emit-xcconfig-env.sh from ${file}. Do not edit."
header_sh="# Generated by scripts/lib/emit-xcconfig-env.sh from ${file}. Do not edit."

emit_header() {
  case "$format" in
    make) printf '%s\n' "$header_make" ;;
    sh)   printf '%s\n' "$header_sh" ;;
  esac
}

if [[ ! -f "$file" ]]; then
  emit_header
  exit 0
fi

# Pass 1: read every KEY\tVALUE row, validate, capture into parallel arrays.
keys=()
values=()
while IFS=$'\t' read -r key value; do
  if [[ "$value" == *$'\n'* ]]; then
    printf 'error: %s in %s contains a newline\n' "$key" "$file" >&2
    exit 2
  fi
  if ! err="$(xcconfig_validate_value "$file" "$key" "$value")"; then
    printf '%s\n' "$err" >&2
    exit 2
  fi
  keys+=("$key")
  values+=("$value")
done < <(awk -f "${script_dir}/xcconfig-parse.awk" -v mode=all "$file")

# Pass 2: emit. Empty-valued keys are skipped so the post-include `?=`
# defaults still apply.
emit_header
for i in "${!keys[@]}"; do
  key="${keys[$i]}"
  value="${values[$i]}"
  if [[ -z "$value" ]]; then
    continue
  fi
  case "$format" in
    make)
      escaped="${value//\$/\$\$}"
      printf '%s ?= %s\n' "$key" "$escaped"
      ;;
    sh)
      # POSIX single-quote escape: close, escaped quote, reopen.
      sq=\'
      sq_esc=\'\\\'\'
      escaped=${value//$sq/$sq_esc}
      printf "%s='%s'\n" "$key" "$escaped"
      ;;
  esac
done
