#!/usr/bin/env bash
# Plain-bash test runner for scripts/lib/emit-xcconfig-env.sh. No external
# framework dependency — the script is small and the assertions are local.
# Run with `make scripts-test` or `bash scripts/test/emit-xcconfig-env.test.sh`.

set -uo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
emit="${repo_root}/scripts/lib/emit-xcconfig-env.sh"

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

pass=0
fail=0
failed_cases=()

note() {
  printf '  %s\n' "$*"
}

run_case() {
  local name="$1"
  if "case_${name}"; then
    pass=$((pass + 1))
    printf '  ok  %s\n' "$name"
  else
    fail=$((fail + 1))
    failed_cases+=("$name")
    printf '  FAIL %s\n' "$name"
  fi
}

assert_eq() {
  local got="$1" want="$2" label="${3:-value}"
  if [[ "$got" != "$want" ]]; then
    note "expected ${label}=[${want}], got [${got}]"
    return 1
  fi
  return 0
}

assert_contains() {
  local haystack="$1" needle="$2" label="${3:-output}"
  if [[ "$haystack" != *"$needle"* ]]; then
    note "expected ${label} to contain [${needle}], got:"
    note "${haystack}"
    return 1
  fi
  return 0
}

# --- cases ---

# Normal value renders correctly in both formats.
case_normal_value() {
  local cfg="${tmpdir}/normal.xcconfig"
  printf 'PLAIN = hello\n' > "$cfg"
  local make_out sh_out
  make_out="$("$emit" --format=make "$cfg")" || return 1
  sh_out="$("$emit" --format=sh "$cfg")" || return 1
  assert_contains "$make_out" 'PLAIN ?= hello' "make output" || return 1
  assert_contains "$sh_out" "PLAIN='hello'" "sh output" || return 1
}

# _HOST containing :// must reject with no stdout (two-phase guarantee).
case_host_scheme_rejection() {
  local cfg="${tmpdir}/bad-host.xcconfig"
  printf 'CATVOX_BAD_HOST = https://nope\n' > "$cfg"
  local rc=0
  local stdout
  stdout="$("$emit" --format=make "$cfg" 2>/dev/null)" || rc=$?
  if [[ "$rc" -eq 0 ]]; then
    note "expected non-zero exit, got 0"
    return 1
  fi
  if [[ -n "$stdout" ]]; then
    note "expected empty stdout on validation failure, got: $stdout"
    return 1
  fi
}

# _HOST containing a path or trailing slash must reject as well.
case_host_path_rejection() {
  local cfg="${tmpdir}/bad-host-path.xcconfig"
  printf 'CATVOX_BAD_HOST = example.com/path\n' > "$cfg"
  local rc=0
  "$emit" --format=make "$cfg" >/dev/null 2>&1 || rc=$?
  [[ "$rc" -ne 0 ]]
}

# _HOST_NAME (longer suffix) is also rejected.
case_host_name_scheme_rejection() {
  local cfg="${tmpdir}/bad-hostname.xcconfig"
  printf 'POSTHOG_API_HOST_NAME = https://nope\n' > "$cfg"
  local rc=0
  "$emit" --format=sh "$cfg" >/dev/null 2>&1 || rc=$?
  [[ "$rc" -ne 0 ]]
}

# Two-phase contract: a valid key emitted before an invalid one must NOT
# appear on stdout when the invalid key fails validation.
case_two_phase_no_partial_output() {
  local cfg="${tmpdir}/mixed.xcconfig"
  cat > "$cfg" <<'EOF'
GOOD_FIRST = ok
CATVOX_BAD_HOST = https://breaks
GOOD_SECOND = also-ok
EOF
  local stdout
  stdout="$("$emit" --format=make "$cfg" 2>/dev/null)" || true
  if [[ -n "$stdout" ]]; then
    note "expected empty stdout, got: $stdout"
    return 1
  fi
}

# Missing file: header-only output, exit 0.
case_missing_file_silent() {
  local cfg="${tmpdir}/does-not-exist.xcconfig"
  local out
  out="$("$emit" --format=make "$cfg")" || return 1
  assert_contains "$out" "Generated by" "header comment" || return 1
  # Header is the only line.
  local nonheader
  nonheader="$(printf '%s\n' "$out" | grep -vE '^#' || true)"
  if [[ -n "$nonheader" ]]; then
    note "expected header-only on missing file, got extra: $nonheader"
    return 1
  fi
}

# Empty value: key is omitted so post-include `?=` fallbacks still apply.
case_empty_value_omitted() {
  local cfg="${tmpdir}/empty.xcconfig"
  printf 'NORMAL = hello\nEMPTY = \n' > "$cfg"
  local out
  out="$("$emit" --format=make "$cfg")" || return 1
  assert_contains "$out" "NORMAL ?= hello" "make output" || return 1
  if printf '%s\n' "$out" | grep -qE '^EMPTY '; then
    note "expected EMPTY to be omitted, found in output"
    return 1
  fi
}

# Make output escapes $ to $$.
case_dollar_escaped_for_make() {
  local cfg="${tmpdir}/dollar.xcconfig"
  # shellcheck disable=SC2016  # literal $$ is the value we want in the xcconfig
  printf 'WITH_DOLLAR = pa$$word\n' > "$cfg"
  local out
  out="$("$emit" --format=make "$cfg")" || return 1
  # shellcheck disable=SC2016  # literal $$$$ is the Make-escaped form of $$
  assert_contains "$out" 'WITH_DOLLAR ?= pa$$$$word' "make output" || return 1
}

# Sh output: single-quote round-trip via source.
case_single_quote_round_trip() {
  local cfg="${tmpdir}/quote.xcconfig"
  printf "QUOTED = it's a trap\n" > "$cfg"
  local fragment
  fragment="$(mktemp "${tmpdir}/frag.XXXX")"
  "$emit" --format=sh "$cfg" > "$fragment" || return 1
  # Source the fragment in a subshell and check the value round-trips.
  local got
  # shellcheck disable=SC1090  # fragment path is generated per test case
  got="$(QUOTED=""; . "$fragment"; printf '%s' "$QUOTED")"
  assert_eq "$got" "it's a trap" "sourced QUOTED" || return 1
}

# Alias keys: both names emitted so the Makefile's post-include
# `CATVOX_IOS_BUNDLE_ID ?= $(CATVOX_PRODUCT_BUNDLE_IDENTIFIER)` fallback works.
case_alias_keys_both_emitted() {
  local cfg="${tmpdir}/alias.xcconfig"
  printf 'CATVOX_IOS_BUNDLE_ID = a\nCATVOX_PRODUCT_BUNDLE_IDENTIFIER = b\n' > "$cfg"
  local out
  out="$("$emit" --format=make "$cfg")" || return 1
  assert_contains "$out" 'CATVOX_IOS_BUNDLE_ID ?= a' "make output" || return 1
  assert_contains "$out" 'CATVOX_PRODUCT_BUNDLE_IDENTIFIER ?= b' "make output" || return 1
}

# Unknown --format and missing argument are usage errors.
case_usage_errors() {
  local rc=0
  "$emit" --format=ruby /dev/null >/dev/null 2>&1 || rc=$?
  if [[ "$rc" -eq 0 ]]; then
    note "expected non-zero exit for --format=ruby"
    return 1
  fi
  rc=0
  "$emit" --format=make >/dev/null 2>&1 || rc=$?
  if [[ "$rc" -eq 0 ]]; then
    note "expected non-zero exit for missing file argument"
    return 1
  fi
}

# Comment-only lines and blank lines are ignored.
case_comments_and_blanks_ignored() {
  local cfg="${tmpdir}/comments.xcconfig"
  cat > "$cfg" <<'EOF'
// header comment
# alt comment

REAL = yes
EOF
  local out
  out="$("$emit" --format=make "$cfg")" || return 1
  assert_contains "$out" 'REAL ?= yes' "make output" || return 1
  if printf '%s\n' "$out" | grep -qE '^(header|alt)'; then
    note "comment leaked into output"
    return 1
  fi
}

# Suite runner.
printf 'emit-xcconfig-env tests\n'
run_case normal_value
run_case host_scheme_rejection
run_case host_path_rejection
run_case host_name_scheme_rejection
run_case two_phase_no_partial_output
run_case missing_file_silent
run_case empty_value_omitted
run_case dollar_escaped_for_make
run_case single_quote_round_trip
run_case alias_keys_both_emitted
run_case usage_errors
run_case comments_and_blanks_ignored

printf '\n%d passed, %d failed\n' "$pass" "$fail"
if [[ "$fail" -ne 0 ]]; then
  printf 'failed: %s\n' "${failed_cases[*]}"
  exit 1
fi
